ProsPyApp/urls.py
from django.urls import path
from ProsPyApp import views
from django.contrib.auth.decorators import login_required

app_name = 'ProsPy'

urlpatterns = [

    path('Index/',  views.Index.as_view(), name='Index'),

    path('Inicio/', login_required(views.Inicio.as_view()), name='Inicio'),
    path('busqueda/', login_required(views.busqueda), name='busqueda'),

    path('', views.Login.as_view(), name='Login'),
    path('Salir/', login_required(views.LogoutUsuario.as_view()), name='Salir'),

    path('ModeloReact/', login_required(views.ModeloReact.as_view()), name='ModeloReact'),
    path('TiempoCultivo/', login_required(views.TiempoCultivo.as_view()), name='TiempoCultivo'),

    path('Admin/', login_required(views.Admin.as_view()), name='Admin'),

    path('LUsuarioLista/', login_required(views.LUsuarioLista.as_view()), name='LUsuarioLista'),
    path('UsuarioLista/', login_required(views.UsuarioLista.as_view()), name='UsuarioLista'),

    path('LUTipoReactor/', login_required(views.LUTipoReactor.as_view()), name='LUTipoReactor'),
    path('TipoReactorlista/', login_required(views.TipoReactorlista.as_view()), name='TipoReactorlista'),
    path('GuardarTipo/', login_required(views.GuardarTipo.as_view()), name='GuardarTipo'),
    path('EditarTipo/<int:pk>/', login_required(views.EditarTipo.as_view()), name='EditarTipo'),
    path('EliminarTipo/<int:pk>/', login_required(views.EliminarTipo.as_view()), name='EliminarTipo'),

    path('LUOrganismo/', login_required(views.LUOrganismo.as_view()), name='LUOrganismo'),
    path('Organismolista/', login_required(views.Organismolista.as_view()), name='Organismolista'),
    path('GuardarOrganismo/', login_required(views.GuardarOrganismo.as_view()), name='GuardarOrganismo'),
    path('EditarOrganismo/<int:pk>/', login_required(views.EditarOrganismo.as_view()), name='EditarOrganismo'),
    path('EliminarOrganismo/<int:pk>/', login_required(views.EliminarOrganismo.as_view()), name='EliminarOrganismo'),

    path('LUReactor/', login_required(views.LUReactor.as_view()), name='LUReactor'),
    path('Reactorlista/', login_required(views.Reactorlista.as_view()), name='Reactorlista'),
    path('GuardarReactor/', login_required(views.GuardarReactor.as_view()), name='GuardarReactor'),
    path('EditarReactor/<int:pk>/', login_required(views.EditarReactor.as_view()), name='EditarReactor'),
    path('EliminarReactor/<int:pk>/', login_required(views.EliminarReactor.as_view()), name='EliminarReactor'),

    path('LUCaBatch/', login_required(views.LUCaBatch.as_view()), name='LUCaBatch'),
    path('CaBatchlista/', login_required(views.CaBatchlista.as_view()), name='CaBatchlista'),
    path('GuardarCaBatch/', login_required(views.GuardarCaBatch.as_view()), name='GuardarCaBatch'),
    path('EditarCaCaBatch/<int:pk>/', login_required(views.EditarCaCaBatch.as_view()), name='EditarCaCaBatch'),
    path('EliminarCaCaBatch/<int:pk>/', login_required(views.EliminarCaCaBatch.as_view()), name='EliminarCaCaBatch'),

    path('LUCaPrediccion/', login_required(views.LUCaPrediccion.as_view()), name='LUCaPrediccion'),
    path('CaPrediccionlista/', login_required(views.CaPrediccionlista.as_view()), name='CaPrediccionlista'),
    path('GuardarCaPrediccion/', login_required(views.GuardarCaPrediccion.as_view()), name='GuardarCaPrediccion'),
    path('EditarCaPrediccion/<int:pk>/', login_required(views.EditarCaPrediccion.as_view()), name='EditarCaPrediccion'),
    path('EliminarCaPrediccion/<int:pk>/', login_required(views.EliminarCaPrediccion.as_view()),
         name='EliminarCaPrediccion'),

    path('CrearUsuario/', views.CrearUsuario.as_view(), name=' CrearUsuario'),
    path('CambiarContraseña', login_required(views.CambiarContraseña), name='CambiarContraseña'),
    path('EditarUsuario/<int:pk>/', login_required(views.EditarUsuario.as_view()), name='EditarUsuario'),
    path('EliminarUsuario/<int:pk>/', login_required(views.EliminarUsuario.as_view()), name='EliminarUsuario'),

    path('EjerciciosLista/', login_required(views.EjerciciosLista.as_view()), name='EjerciciosLista'),
    path('ActualizarCaBatch/<int:pk>', login_required(views.ActualizarCaBatch.as_view()), name='ActualizarCaBatch'),
    path('EliminarCaBatch/<int:pk>', login_required(views.EliminarCaBatch.as_view()), name='EliminarCaBatch'),

    path('ActualizarPrediccion/<int:pk>', login_required(views.ActualizarPrediccion.as_view()),
         name='ActualizarPrediccion'),
    path('EliminarPrediccion/<int:pk>', login_required(views.EliminarPrediccion.as_view()), name='EliminarPrediccion'),

    path('CompararBatch/', login_required(views.CompararBatch.as_view()), name='CompararBatch'),
    path('CompararTiempo/', login_required(views.CompararTiempo.as_view()), name='CompararTiempo'),

    path('ImprimirTiempo/', views.ImprimirTiempo.as_view(), name='ImprimirTiempo'),

    path('Imprimirbatch/', views.Imprimirbatch.as_view(), name='Imprimirbatch'),

]

Tesis/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProsPyApp.urls')),
    path('', include('RecuperarContraseña.urls')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

templates/config_usu.html
{% extends "inicio.html" %}
{% load static %}
{% block title %}
    Ajustes
{% endblock %}

{% block Titulo %}

    {% if user.is_authenticated %}
        {{ user.email }}
    {% endif %}
{% endblock %}
{% block content %}

    <div class="row">
        <!-- left column -->
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Cuenta</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->

                <form method="POST">

                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Contraseña actual</label>
                            {{ form.old_password }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">NUeva Contraseña</label>
                            {{ form.new_password1 }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Confirmar Nueva Contraseña</label>
                            {{ form.new_password2 }}
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
        <!--/.col (left) -->
        <!-- right column -->
    </div>
{% endblock %}






     

templates/editar_cabatch_modal.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Edicion : {{ object }}</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="form_editar" method="POST" action="{% url 'ProsPy:EditarCaCaBatch' object.pk %}">
            {% csrf_token %}
            <div class="modal-body">
                <div id="error_editar">
                    {{ form.as_p }}
                    {{ user.username }}
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" onclick="cerrar_modal_editar()">Cancelar</button>
                <button id="boton_creacion" type="button" class="btn btn-primary" onclick="editarcabatch();">Aceptar
                </button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div>


<style type="text/css">
    label {
        width: 90px;
        float: left;
        text-align: left
    }

</style>

templates/editar_reactor_modal.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Edicion de : {{ object }}</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="form_editar" method="POST" action="{% url 'ProsPy:EditarReactor' object.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
                <div id="error_editar">
                    {{ form.as_p }}
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" onclick="cerrar_modal_editar();">Cancelar</button>
                <button id="boton_creacion" type="button" class="btn btn-primary" onclick="editarreactor()">Aceptar</button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div>

<style type="text/css">
    label {
        width: 200px;
        float: left;
        text-align: left
    }

</style>

templates/eliminar_cabatch_modal.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Eliminar</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% csrf_token %}
        <div class="modal-body">
            <h4>Estas seguro de eliminar {{ object.pk }} </h4>
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" onclick="cerrar_modal_eliminar();">Cancelar</button>
            <button id="boton_creacion" type="button" class="btn btn-danger" onclick="eliminarcabatch({{ object.pk }});">
                Aceptar
            </button>
        </div>
    </div>
    <!-- /.modal-content -->
</div>

templates/password_reset_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    {% load static %}

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->

<div class="lockscreen-wrapper" style="max-width: 500px">
    <div class="lockscreen-logo">
        <a><b>Pros</b>Py</a>
    </div>

    <!-- User name -->
    <div class="lockscreen-name"><h1>Se envió el restablecimiento de contraseña</h1></div>
    <h5>Le enviamos instrucciones por correo electrónico para configurar su contraseña, si existe una cuenta con el
        correo electrónico que ingresó. Deberías recibirlos en breve.</h5><br>
    <h6 style="width: 60%; margin: 0 auto">Si no recibe un correo electrónico, asegúrese de haber ingresado la dirección
        con la que se registró y verifique su carpeta de correo no deseado.</h6><br>


    <div class="text-center">
        <a class="btn btn-primary btn-block" href="{% url 'ProsPy:Login' %}">Login</a>
    </div>
    <div class="lockscreen-footer text-center">
        Copyright &copy; 2020-2021 <b><a class="text-black">ProsPy</a></b><br>
    </div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'jquery/jquery.min.js' %}"></script>
</body>
</html>






{% block content %}
    <div class="text-center" style="width: 80%; margin: 0 auto">

    </div>
    <
{% endblock %}

templates/registro_caprediccion_modal.html
<div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Prediccion</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="form_reactor" method="POST" action="{% url 'ProsPy:GuardarCaPrediccion' %}">
            {% csrf_token %}
            <div class="modal-body">
                <div id="error_reactor">
                    {{ form.as_p }}
                    {{ user.username }}
                </div>
            </div>
            <div class="modal-footer justify-content-between ">
                <button type="button" class="btn btn-default" onclick="cerrar_modal_prediccion();">Cancelar</button>
                <button id="boton_creacion" type="button" class="btn btn-primary" onclick="registrarcaprediccion();">Aceptar</button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div>

<style type="text/css">
    label {
        width: 90px;
        float: left;
        text-align: left
    }

</style>

templates/registro_modal_tipo.html
<div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Tipo Reactor</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="form_reactor" method="POST" action="{% url 'ProsPy:GuardarTipo' %}">
            {% csrf_token %}
            <div class="modal-body">
                <div id="error_registro">
                    {{ form.as_p }}

                </div>
            </div>
            <div class="modal-footer justify-content-between ">
                <button type="button" class="btn btn-default" onclick="cerrar_modal_guardar();">Cancelar</button>
                <button id="boton_creacion" type="button" class="btn btn-primary" onclick="registrartiporeactor();">Aceptar</button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div>

<style type="text/css">
    label {
        width: 110px;
        float: left;
        text-align: left
    }

</style>

templates/tabla_tiporeactor.html
{% extends "base.html" %}
{% load static %}
{% csrf_token %}

{% block title %}
    Listado de Reactores

{% endblock %}

{% block extracss %}


{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Listado tipo de reactor.</h3>
                </div>
                <!-- /.card-header -->

                <div class="card-body">

                    <div id="tablatipo_wrapper" class="dataTables_wrapper dt-bootstrap4">

                        <table id="tablatipo" class="table table-bordered table-striped dataTable dtr-inline">
                            <thead>
                            <div class="row">
                                <div class="col-xs-12 col-md-8"></div>
                                <div class="col-xs-6 col-md-4">
                                    <button type="submit" class="btn btn-block btn-outline-info"
                                            onclick="abrir_modal_guardar('{% url 'ProsPy:GuardarTipo' %}');">Registrar
                                    </button>
                                </div>
                            </div>
                            <tr>
                                <th><i class="fa fa-bullhorn"></i>#</th>
                                <th><i class="fa  "></i> Descripcion</th>
                                <th><i class="fa  "></i> Especificacion</th>
                                <th><i class="fa  "></i> Tipo</th>
                                <th><i class="fa  "></i> Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        td {
            white-space: nowrap;
            text-overflow: ellipsis;
            overflow: hidden;
        }
    </style>


    <div class="modal fade" id="registro_modal">
    </div>
    <div class="modal fade" id="eliminar_modal">
    </div>
    <div class="modal fade" id="editar_modal">
    </div>


{% endblock %}

{% block extrajs %}

    <!-- Bootstrap 4 -->
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'jszip/jszip.min.js' %}"></script>
    <script src="{% static 'pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'datatables-buttons/js/buttons.print.min.js' %}"></script>
    <!-- AdminLTE App -->

    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <script src="{% static 'ajax.js' %}"></script>
    <script src="{% static 'modal.js' %}"></script>

    <script src="{% static 'validaciones.js' %}"></script>

    <link href="{% static 'sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'sweetalert2/sweetalert2.min.js' %}"></script>

{% endblock extrajs %}

templates/tiempo_cultivo.html
{% extends "inicio.html" %}
{% load static %}

{% block title %}
    Prediccion Tiempo
{% endblock %}

{% block extracss %}
    <script src="{% static 'Highcharts/highcharts.js' %}"></script>
    <script src="{% static 'Highcharts/modules/series-label.js' %}"></script>
    <script src="{% static 'Highcharts/modules/exporting.js' %}"></script>
    <script src="{% static 'Highcharts/modules/export-data.js' %}"></script>
    <script src="{% static 'Highcharts/modules/accessibility.js' %}"></script>


{% endblock %}

{% block content %}


    <div class="row">
    <!-- left column -->
    <div class="col-md-4">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Predicción del tiempo de cultivo</h3>
                <button type="button" class=" btn btn-xs btn-success formula" style=" float:right; ">
                    <a href="#"> </a>
                    Formulas
                </button>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form>
                <div class="card-body">
                    <div class="showback">
                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">X</div>
                                <div style="width:70px; float:right;margin-right:100px">Kg <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfox "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="X" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>
                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">V</div>
                                <div style="width:70px; float:right;margin-right:100px">m3 <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfov "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="V" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>
                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">So</div>
                                <div style="width:70px; float:right;margin-right:100px">m3 <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfoso "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="So" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>
                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">Umax</div>
                                <div style="width:70px; float:right;margin-right:100px">H-1 <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfoumax "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="Umax" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>
                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">Y(x/s)</div>
                                <div style="width:70px; float:right;margin-right:100px">Kg/Kg <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfoy "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="Y" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>


                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">Sf</div>
                                <div style="width:70px; float:right;margin-right:100px">g/L <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfosf "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="Sf" class="small" size="2"
                                           style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>

                        <div class="blockslider">
                            <div>
                                <div style="width:60px; float:left; text-align:left">Tb</div>
                                <div style="width:70px; float:right;margin-right:100px">h <a href="#"
                                                                                                style="width:10px; float:right; "><i
                                        class="fa fa-question-circle swalDefaultInfotb "></i></a></div>
                                <div style="margin-left:60px">
                                    <input id="Tb" class="small" size="2" style="color: #000000" onkeypress="return filterFloat(event,this);"></div>
                            </div>
                        </div>

                        <div class="blockslider">
                            <strong>
                      <span class="rateLbl text-primary">
                        <font class="small" style="float:left;margin-left:30px ">Tiempo face estacionaria:  <span
                                id="cont1" style="color: #000000"></span>  h</font>
                     </span>
                            </strong>
                        </div>
                        <div class="blockslider">
                            <strong>
                      <span class="rateLbl text-primary ">
                        <font class="small" style="float:left;margin-left:30px ">Densidad celular final 100% :  <span
                                id="cont2" style="color: #000000"></span>  </font>
                     </span>
                            </strong>
                        </div>

                        <div class="blockslider">
                            <strong>
                      <span class="rateLbl text-primary">
                        <font class="small" style="float:left;margin-left:30px ">Tiempo face estacionaria consumo:
                            <span id="cont3"></span>
                            <span id="cont5" style="color: #000000"></span>  h</font>
                     </span>
                            </strong>
                        </div>
                        <div class="blockslider">
                            <strong>
                      <span class="rateLbl text-primary">
                        <font class="small" style="float:left;margin-left:30px ">Densidad celular consumo
                            <span id="cont6"></span>
                            <span id="cont4" style="color: #000000"></span>  </font>
                     </span>
                            </strong>
                        </div>

                    </div>
                </div>
                <div class="card-footer">
                    <div class="col-12">
                        <a onclick="abrir_modal_imprimir('{% url 'ProsPy:ImprimirTiempo' %}');" rel="noopener"
                           target="_blank" class="btn btn-default"><i class="fa fa-print"></i><font
                                style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                            Impresión</font></font></a>

                        <button type="button" onclick="abrir_modal_prediccion('{% url 'ProsPy:GuardarCaPrediccion' %}','{{ user.username }}');"
                            class="btn btn-primary float-right">Guardar
                    </button>

                </div>


                </div>

            </form>
        </div>


    </div>
    <!--/.col (left) -->
    <!-- right column -->
    <div class="col-md-8">
        <!-- Form Element sizes -->
        <div class="card card-success">
            <div class="showback">
                <div id="predicctiempo">
                </div>
            </div>
        </div>

    </div>

     <div class="modal fade" id="reactor_modal">
    </div>
     <div class="modal fade" id="imprimir_modal">
     </div>


{% endblock %}

{% block extrajs %}

    <script src="{% static 'ajax.js' %}"></script>
    <script src="{% static 'predicciontiempo.js' %}"></script>
    <script src="{% static 'modal.js' %}"></script>
    <script src="{% static 'validaciones.js' %}"></script>

    <!-- Bootstrap 4 -->
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <link href="{% static 'sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'sweetalert2/sweetalert2.min.js' %}"></script>

      <script>
        $(function () {
            var Toast = Swal.mixin({
                toast: true,
                position: 'bottom ',
                showConfirmButton: false,
                timer: 5000
            });

            function onOpen() {
                var zippi = new Audio('/media/bambu_1.mp3')
                zippi.play();
            }

            $('.swalDefaultInfox').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Concentracion de celulas',
                    onOpen
                })
            });
            $('.swalDefaultInfov').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Variacion de volumen',
                    onOpen
                })
            });
            $('.swalDefaultInfoso').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Consentracion de sustrato de alimentacion',
                    onOpen
                })
            });
            $('.swalDefaultInfoumax').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Velocidad maxima de crecimiento',
                    onOpen
                })
            });
            $('.swalDefaultInfoy').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Rendimiento de Biomasas',
                    onOpen
                })
            });
            $('.swalDefaultInfosf').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Concentración de sustrato en el líquido dentro del biorreactor',
                    onOpen
                })
            });
            $('.swalDefaultInfotb').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Tiempo para alcanzar la face estacionaria',
                    onOpen
                })
            });
              $('.formula').click(function () {
                Toast.fire({
                    imageUrl: '/media/img/tiempoformula.jpeg',
                    imageWidth: 400,
                    imageHeight: 300,
                    imageAlt: 'Custom image',
                    onOpen
                })
            });
        });
    </script>

{% endblock extrajs %}